version: "3.9"
services:
  mysql:
    container_name: mysql8
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: app123
      TZ: Asia/Seoul
    volumes:
      - mysql:/var/run/mysqld
    ports:
      - 3306:3306
    networks:
      - app
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216

volumes:
  mysql:

networks:
  app:
    driver: bridge